### PR TITLE
Testing small changes

### PR DESCRIPTION
**Pull request by bensait41**
I added some comments

### CODE REVIEW

**Review by Adamsezer — APPROVED** [review]
Good job. Ok.

**Review by Adamsezer — APPROVED** [review]
ok.

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok.

**Review by Adamsezer — APPROVED** [review]
ok

**Review by Adamsezer — APPROVED** [review]
ok

**Review by bensait41 — COMMENTED** [review]
all okay

**Review by Adamsezer — COMMENTED** [review]
ok

**Pull request closed without merging**
