### PR TITLE
I want to Merge the empty step defs, featues files and pages

### PR DESCRIPTION
**Pull request by bensait41**
Hi, I have just created pages, step definitions and feature files. But all are empty, as a team we need to fill them in. Please review

### CODE REVIEW

**Review by selmanland — APPROVED** [review]
good job

**Review by tarikbuyuk — APPROVED** [review]

**Review by tarikbuyuk — APPROVED** [review]
TEBRIKLER

**Review by tarikbuyuk — APPROVED** [review]
NEED CHANGE

**Review by tarikbuyuk — CHANGES_REQUESTED** [review]
NEED CHANGE

**Review by tarikbuyuk — COMMENTED** [review]
WHY

**Pull request merged**
