### PR TITLE
NagativeStepDefs sth added

### PR DESCRIPTION
**Pull request by bensait41**

### CODE REVIEW

**Review by tarikbuyuk — APPROVED** [review]
duzeltilmeli

**Review by tarikbuyuk — APPROVED** [review]
ok

**Review by tarikbuyuk — APPROVED** [review]
ok

**Review by tarikbuyuk — CHANGES_REQUESTED** [review]
change need

**Comment by bensait41** [comment]
why not merging????

**Comment by tarikbuyuk** [comment]
needs to change

**Comment by bensait41** [comment]
hello

**Review by tarikbuyuk — APPROVED** [review]
ok

**Pull request closed without merging**
